server:
    port: 6021
    context-path: /prod-svc
    undertow:
        accessLog:
            enabled: true
            pattern: "%t %a \"%r\" %s (%D ms)"
            dir: /jtpf/logs/${spring.application.name}
spring:
#    profiles:
#        active: local_dev
    application:
        name: prod-svc
#    zipkin:
#        base-url: http://localhost:9761
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://10.30.131.42/jtproducts?characterEncoding=utf-8
        hikari:
            username: jtproducts
            password: "@2018#"
            driver-class-name: com.mysql.jdbc.Driver
            minimum-idle: 1
            maximum-pool-size: 5
            pool-name: dbcp1
            connection-test-query: select 1
    redis:
        host: 172.16.4.239
        port: 6379
        timeout: 3000
        pool:
            max-idle: 10
            max-wait: 10000
        max-active: 20
        maxTotal: 20

management:
    security:
        enabled: false
        
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
    instance:
        prefer-ip-address: true
        hostname: ${spring.cloud.client.ipAddress}
        instance-id: ${spring.cloud.client.ipAddress}:${server.port}
        
mybatis:
  type-aliases-package: com.jt.plt.product.entity
  mapper-locations: classpath:mapper/*.xml
  
mapper:
  mappers: com.jt.plt.product.base.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
        